version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    #ここは変えないで！ユーザー名とパスワードは指定してある.本番環境まで触らない
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      #ここのデータベース名変えたらdatabase.ymlのdevelopmentのデータベース名も変えてね！
      POSTGRES_DB: esnoon_development
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      #前がホスト側、後ろがコンテナ側.ホスト側のポート埋まってたら変えてね！
      #デフォルトは3000:3000
      - "3000:3000"
    depends_on:
      - db
    volumes:
      #ここで必ずローカルの開発コピーディレクトリを指定する！
      - /Users/mao/Documents/rails_dev:/app_dev
      #データベースの設定しなくていいようにしてるから、こっちは絶対触らない.
      - ./rails-temp:/rails-temp
    #ここは変えないで！ユーザー名とパスワードは指定してある.本番環境まで触らない
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

volumes:
  db-data:
