default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# 開発環境用のデータベース名（下の `database:` を docker-compose.yml の POSTGRES_DB と同じにする）
development:
  <<: *default
  #ここの名前をcompose.ymlの方と一致させてね！
  database: esnoon_development

#テスト環境用のデータベース名(変えたければ変えてね)
test:
  <<: *default
  database: esnoon_test

#本番環境用のデータベース名(変えたければ変えてね)
production:
  <<: *default
  database: esnoon_production
